### PR TITLE
Fix the line ending issue

### LINKED ISSUE #9: Newlines broken in output pyproject.toml
I ran the `conduct release` command and it finished successfully. However, when pushing the modified `pyproject.toml` files to GitHub, I noticed that the Spine-Database-API GitHub actions failed because Python's toml library couldn't parse the files. In PyCharm, `pyproject.toml` shows extra new line on each line so I suppose `conductor` somehow messes those up. Manually replacing all newlines by with comes out from Return key in Windows fixes `pyproject.toml`.

### PR DESCRIPTION
**Pull request by suvayu**
Fixes #9

@soininen @PekkaSavolainen could you please check?

### CODE REVIEW

**Comment by soininen** [comment]
Extra new lines are now gone but the script still seems to unnecessarily change the line endings making Git to believe that every line in `pyproject.toml` has been modified.

**Comment by soininen** [comment]
Actually, I'm not sure what happens there. The line endings are correct CRLF before and after running `conduct release -c release.toml` but `git diff HEAD~1` somehow shows modified line endings like

```
+[project]^M
```

for the entire `pyproject.toml` file. Why that `^M`?

**Comment by soininen** [comment]
Okay, what fixes the problem is to add `.gitattributes` file to the Toolbox repository that defines the newline behavior explicitly. It seems to be the recommended practice anyway so I think I'll just add the files to all four repositories now.

**Review by soininen — APPROVED** [review]
The newlines seem to be working after adding `.gitattributes` to the Toolbox repos.

**Comment by PekkaSavolainen** [comment]
Unfortunately, I still see the problem even after `.gitattributes` was added. The newlines are now reported as `^M` when doing `git diff`. 

I thought `gitpython` might ignore my global git settings so I tried adding `autocrlf = true` to my local Conductor repo but that did nothing. Now, I'm wondering if it has something to do with the editor `gitpython` may use because it opens Notepad for me as well for editing the commit message.

**Comment by soininen** [comment]
> Unfortunately, I still see the problem even after .gitattributes was added. 

Strange, I do not see any newline issues anymore on my system.

**Comment by soininen** [comment]
I take back what I said about not having newline issues. There is something fishy still.

**Comment by suvayu** [comment]
> Is this due to some Git config issue? I noticed that the commit editor that gets launched when I run `conduct release` is Notepad and not Notepad++ which I have set for my installed Git. 

Could you tell me how this is configured?  Is it whatever is returned by:

    $ git config --get core.editor

What is the value of the above command for you?

> Are we using a different Git here with different line ending settings?

This is a bit difficult to answer.  We are using the Git repo from Python using `GitPython`.  As far as I understand the implementation, it uses the so-called "plumbing commands", which means it's possible these commands don't check user config since they are building blocks of the Git CLI we are used to.

I'll look at the line-ending issues a bit later, I'm working on a different project today.

**Comment by PekkaSavolainen** [comment]
```
(conductor) C:\data\GIT\SPINETOOLBOX>git config --get core.editor
"C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
```

So this is notepad++ as it should be and not notepad.

> I'll look at the line-ending issues a bit later, I'm working on a different project today.

Sure, this is not top priority by any means.

**Pull request merged**
